### ISSUE TITLE
application.properties를 application.yml로 변경

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#11]
## Description

yaml의 형식이 properties보다 계층적이고 직관적이다. 신규 프로젝트의 경우 properties 대신 yml을 많이 쓴다.

우리도 yml 형식으로 작성하고자 하지만, application.yml로 변경 시 현재 서버가 동작하며 자동 생성해주는 applicaiton-settings.properties가 문제가 된다.

yml로 변경하게 되면 properties 자동 생성 로직을 수정해야 한다.

## Tasks

- [x] .properties 파일을 .yml로 변경
- [x] 프로젝트 처음 실행 시 application-settings.yml 자동 생성 로직 구현

## References

예시

* .properties  
  ```
  spring.datasource.username=user
  spring.datasource.url=jdbc:mysql://localhost:3306/chatfoodie
  spring.datasource.password=password
  ```
* .yml  
  ```
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/chatfoodie
      username: user
      password: password
  ```

> snakeyml 라이브러리를 사용하면 yml을 클래스로 매핑하여 조작할 수 있다는 것 같다.
